name: Build and Upload to S3

on:
  push:
    branches:
      - master # Trigger workflow on pushes to the main branch

jobs:
  build-and-upload:
    runs-on: self-hosted # Menggunakan self-hosted runner

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install latest Node.js and npm
        run: |
          curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
          sudo apt-get install -y nodejs
          node -v # 
          npm -v  # 

      # Step 2: Install dependencies and build project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 3: Compress the build folder
      - name: Compress build folder
        run: |
          cd build
          zip -r ../build.zip .

      # Step 4: Upload .zip file to S3
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp build.zip s3://artifactcicdvprofile14/
